### ISSUE TITLE
vendure-plugin-google-cloud-tasks needs `body-parser`

### ISSUE THREAD

**Issue by skid** [martijnvdbrug/pinelab-vendure-plugins#1]
I'm using vendure-plugin-google-cloud-tasks in one of my projects and I realized that the POST body is empty if I don't apply `body-parser` (e.g. json) as a middleware on the `cloud-tasks` route.

This causes the task handler to error out id you don't parse the request body elsewhere.
Maybe you want to add it as a middleware in your plugin init code, or I'm glad to make a PR when I get freed up a bit.

**Comment by skid** [comment]
Looking at my repo at that date, I see it was version `1.2.0`.

**Comment by martijnvdbrug** [comment]
Fixed in #2 and release as [v1.2.6](https://www.npmjs.com/package/vendure-plugin-google-cloud-tasks/v/1.2.6)
