### ISSUE TITLE
tmp package missing for vendure-plugin-google-storage-assets

### ISSUE THREAD

**Issue by toonjanssens** [martijnvdbrug/pinelab-vendure-plugins#5]
When I install the vendure-plugin-google-storage-assets plugin I got this  `Error: Cannot find module 'tmp'`
It was easily solved by installing the tmp package, so I think it's a missing dependency in the plugin package.json?

**Comment by martijnvdbrug** [comment]
Hi @toonjanssens, I think you're right. It's working on my end, probably because its a subdependency of Vendure somewhere. I will create a fix

**Comment by martijnvdbrug** [comment]
The patched version 1.3.3 now includes the tmp dependency
